name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build-docker:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build service
        run: docker build .

  build-lint-test:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Lint
        run: bun run lint

      - name: Integration tests
        run: |
          bun dist/index.js --lineupId=USA-DITV751-X --timespan=3 --postalCode=80020 --outputFile=dtv.xml
          bun dist/index.js --lineupId=USA-OTA80020 --timespan=3 --postalCode=80020 --outputFile=ota.xml

          # Error if they are the same
          if cmp -s dtv.xml ota.xml; then
            echo "DTV and OTA outputs are the same, which is unexpected."
            exit 1
          fi
