name: Nightly Release

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  check:
    name: Check if code changed in 24h
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.code-change.outputs.should-run }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Check if code has changed within 24 hours
        id: code-change
        run: |
          if [[ $(git rev-list --after="24 hours" --first-parent HEAD) ]]; then
            echo "should-run=true" >> $GITHUB_OUTPUT
          else
            echo "should-run=false" >> $GITHUB_OUTPUT
          fi

  docker:
    name: Nightly Build and Release Docker image
    needs: check
    if: needs.check.outputs.should-run == 'true'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-publish.yaml
    with:
      tags: |
        type=sha,prefix=,format=short
        type=raw,value=latest
